language: haskell

matrix:
  include:
    - env: GHC=7.10.2 RESOLVER=lts-3 LLVM=3.5
    - env: GHC=7.8.4 RESOLVER=lts-2 LLVM=3.4

sudo: false
cache:
  directories:
    - $HOME/.stack/

before_install:
  - mkdir -p ~/.local/bin/
  - travis_retry curl -L https://www.stackage.org/stack/linux-x86_64 | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'
  - export PATH=~/.local/bin:$PATH

addons:
  apt:
    sources:
      - llvm-toolchain-precise-3.5
      - ubuntu-toolchain-r-test
    packages:
      - llvm-3.4
      - llvm-3.5
      - llvm-3.4-runtime
      - llvm-3.5-runtime
      - libllvm3.4
      - libllvm3.5
      - gcc-5

install:
  - ./.travis_long stack --no-terminal setup --resolver=$RESOLVER
  - ./.travis_long stack --no-terminal build --ghc-options "-pgmc gcc-5 -pgmlo opt-$LLVM -pgmlc llc-$LLVM" --test --bench --only-snapshot --resolver=$RESOLVER

script:
  - echo "Running tests with SIMD support disabled"
  - stack --no-terminal build --flag=reedsolomon:-SIMD --pedantic --ghc-options "-pgmc gcc-5 -pgmlo opt-$LLVM -pgmlc llc-$LLVM" --test --test-arguments "+RTS -N2" --bench --no-run-benchmarks --resolver=$RESOLVER
  - stack --resolver=$RESOLVER clean
  - echo "Running tests with default settings (SIMD support enabled)"
  - stack --no-terminal build --pedantic --ghc-options "-pgmc gcc-5 -pgmlo opt-$LLVM -pgmlc llc-$LLVM" --test --test-arguments "+RTS -N2" --bench --resolver=$RESOLVER

  - stack --resolver=$RESOLVER exec reedsolomon-simple-bench 5 2 $(( 5 * 1024 * 1024 ))
  - stack --resolver=$RESOLVER exec reedsolomon-simple-bench 10 2 $(( 10 * 1024 * 1024 ))
  - stack --resolver=$RESOLVER exec reedsolomon-simple-bench 10 4 $(( 10 * 1024 * 1024 ))
  - stack --resolver=$RESOLVER exec reedsolomon-simple-bench 50 20 $(( 50 * 1024 * 1024 ))
  - stack --resolver=$RESOLVER exec reedsolomon-simple-bench 10 4 $(( 160 * 1024 * 1024 ))
