language: C

branches:
  except:
    - /^appveyor-.*$/
    - /^circleci-.*$/

matrix:
  include:
    # Stackage LTS-3 uses GHC-7.10.2, which relies on LLVM 3.5
    - env: RESOLVER=lts-3 LLVM=3.5
    # Stackage LTS-2 uses GHC 7.8.x, which relies on LLVM 3.4
    - env: RESOLVER=lts-2 LLVM=3.4
    # Current nightly uses GHC 7.10.x
    - env: RESOLVER=nightly LLVM=3.5
    - env: RESOLVER=lts-3
      os: osx

sudo: false
cache:
  directories:
    - $HOME/.stack/

before_install:
  - mkdir -p ~/.local/bin/
  - case "$TRAVIS_OS_NAME" in
      linux)
        travis_retry curl -L https://www.stackage.org/stack/$TRAVIS_OS_NAME-x86_64 | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack';
        export GHC_OPTIONS="-pgmc gcc-5 -pgmlo opt-$LLVM -pgmlc llc-$LLVM";
        export LLVM_FLAG=LLVM;
        export CC=gcc-5;;
      osx)
        travis_retry curl -L https://www.stackage.org/stack/$TRAVIS_OS_NAME-x86_64 | tar xz --strip-components=1 -C ~/.local/bin '*/stack';
        export GHC_OPTIONS="";
        export LLVM_FLAG=-LLVM;;
    esac
  - export PATH=~/.local/bin:$PATH

addons:
  apt:
    sources:
      - llvm-toolchain-precise-3.5
      - ubuntu-toolchain-r-test
    packages:
      - libgmp-dev
      - llvm-3.4
      - llvm-3.5
      - llvm-3.4-runtime
      - llvm-3.5-runtime
      - libllvm3.4
      - libllvm3.5
      - gcc-5

install:
  - pushd cbits; autoreconf -vi; popd
  - ./.travis_long stack --no-terminal setup --resolver=$RESOLVER
  - ./.travis_long stack --no-terminal build --ghc-options "$GHC_OPTIONS" --test --bench --only-snapshot --resolver=$RESOLVER

script:
  - echo "Running tests with SIMD support disabled"
  - stack --no-terminal build --flag=reedsolomon:-SIMD --flag=reedsolomon:$LLVM_FLAG --pedantic --ghc-options "$GHC_OPTIONS" --test --test-arguments "+RTS -N2" --bench --no-run-benchmarks --resolver=$RESOLVER
  - stack --resolver=$RESOLVER clean
  - echo "Running tests with default settings (SIMD support enabled)"
  - stack --no-terminal build --flag=reedsolomon:$LLVM_FLAG --pedantic --ghc-options "$GHC_OPTIONS" --test --test-arguments "+RTS -N2" --bench --resolver=$RESOLVER

  - stack --resolver=$RESOLVER exec reedsolomon-simple-bench 5 2 $(( 5 * 1024 * 1024 ))
  - stack --resolver=$RESOLVER exec reedsolomon-simple-bench 10 2 $(( 10 * 1024 * 1024 ))
  - stack --resolver=$RESOLVER exec reedsolomon-simple-bench 10 4 $(( 10 * 1024 * 1024 ))
  - stack --resolver=$RESOLVER exec reedsolomon-simple-bench 50 20 $(( 50 * 1024 * 1024 ))
  - stack --resolver=$RESOLVER exec reedsolomon-simple-bench 10 4 $(( 160 * 1024 * 1024 ))
