#!/bin/bash -ue

set -ue

set +e
# The `tr` below turns Windows path separators into Unix ones for the `grep` to
# succeed.
echo $@ | tr '\\' '/' | grep "Data/ReedSolomon/Galois/SIMD\.[a-z_]*o" > /dev/null 2>&1
RC1=$?
# Detect GHCi mode (to support `cabal repl`)
echo $@ | grep \\-\\-interactive > /dev/null 2>&1
RC2=$?

test ${RC1} -eq 0 -o ${RC2} -eq 0
RC=$?
set -e

if test ${RC} -eq 0; then
    exec $@ ${CABAL_BUILD_DIR}/cbits/libreedsolomon_*_a-reedsolomon.o \
            ${CABAL_BUILD_DIR}/cbits/reedsolomon_dispatch.o
else
    exec $@
fi
